name: Fuzz
on:
  schedule:
    - cron: '0 21 * * *' # run at 9 PM UTC
  # Allow manual runs
  workflow_dispatch:
env:
  CC: clang
jobs:
  fuzz:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [fuzz, fuzz_tls]
    name: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 2 }
    - run: make -C test ${{ matrix.target }}
